#
# Hass Blueprint:: grid_undervolted_alert.yml
#
# Linter:: yaml-lint
#
# Copyright 2023, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matt@ahrenstein.com
#
# See LICENSE
#
blueprint:
  name: Grid Undervolted Alert
  description:  If the Tesla charger is detecting lower than usual voltage, alert on possible power flickering.
  domain: automation
  source_url: https://github.com/ahrenstein/hass-blueprints/blob/main/blueprints/grid_undervolted_alert/grid_undervolted_alert.yml
  # Inputs used to determine the trigger
  input:
    sns_topic:
      name: AWS SNS Topic
      description: 'An AWS SNS Topic to receive alerts when the grid is undervolted.'
      selector:
        target:
    undervoltage:
      name: Undervoltage threshold
      description: Voltage BELOW this number will trigger an alert
      selector:
        action:

# Events that trigger the automation.
# In this case we just use cron
trigger:
  - platform: numeric_state
      entity_id: sensor.tesla_wall_connector_grid_voltage
      for:
        hours: 0
        minutes: 0
        seconds: 2
      below: {{ undervoltage }}

# The actions we are taking
action:
  - service: notify.sns_important_alerts
    data:
      target: {{ sns_topic }}
      title: Grid Power Undervolted
      message: >-
        The Tesla Charger is detecting an undervolted power grid. Expect power
        flickering due to a voltage level below {{ undervoltage }}

mode: single
max_exceeded: silent
